version: '2'
services:
  node:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: node-server
    volumes:
      - ./backend:/home/backend
    ports:
      - "3001:3001"
    links:
      - mongo
    command: npm run dev

  react:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: react-server
    volumes:
      - ./client:/home/client
    ports:
      - "3000:3000"
    links:
      - node
    command: npm start

  mongo:
    image: mongo:3.7
